#!/bin/sh /etc/rc.common

START=99
STOP=15


CLASH="/etc/clash/clash"
CLASH_CONFIG="/etc/clash"
CRON_FILE="/etc/crontabs/root"

USE_PROCD=1

revert_dns() {
#=========================================================================================================================== 
	uci del dhcp.@dnsmasq[-1].server
	uci set dhcp.@dnsmasq[0].resolvfile=/tmp/resolv.conf.auto
	uci set dhcp.@dnsmasq[0].noresolv=0
	uci commit dhcp
#=========================================================================================================================== 	
}

add_cron(){
#=========================================================================================================================== 
	sed -i '/clash.log/d' $CRON_FILE
	echo '0 0 * * 0 echo "" > /tmp/clash.log' >> $CRON_FILE
	[ -n "$(grep -w "/usr/share/clash/clash.sh" $CRON_FILE)" ] && sed -i '/\/usr\/share\/clash\/clash.sh/d' $CRON_FILE
	auto=$(uci get clash.config.auto_update 2>/dev/null)
	if [ $auto -eq 1 ]; then
	[ -z "$(grep -w "/usr/share/clash/clash.sh" $CRON_FILE)" ] && echo "0 $(uci get clash.config.auto_update_time 2>/dev/null) * * * /usr/share/clash/clash.sh" >> $CRON_FILE
	[ -z "$(grep -w "/etc/init.d/clash" $CRON_FILE)" ] && echo "05 0 * * * /etc/init.d/clash restart" >> $CRON_FILE
	fi
	crontab $CRON_FILE
#=========================================================================================================================== 	
}

del_cron(){
#=========================================================================================================================== 
	sed -i '/clash/d' $CRON_FILE
	sed -i '/clash.log/d' $CRON_FILE
	/etc/init.d/cron restart
#=========================================================================================================================== 	
}


yml_change(){
#===========================================================================================================================
		mode=$(uci get clash.config.mode 2>/dev/null)
		da_password=$(uci get clash.config.dashboard_password 2>/dev/null)
		proxy_port=$(uci get clash.config.proxy_port 2>/dev/null)
		
if [ $mode -eq 1 ];  then

		#sed -i "/dns:/i\#clash-openwrt" /etc/clash/config.yml
        	#sed -i "/#clash-openwrt/a\#=============" /etc/clash/config.yml
		#sed -i '1,/#clash-openwrt/d' /etc/clash/config.yml
		

		#sed -i "1i\port: 7890" /etc/clash/config.yml
		#sed -i "2i\socks-port: 7891" /etc/clash/config.yml
		#sed -i "3i\redir-port: ${proxy_port}" /etc/clash/config.yml
		#sed -i "4i\allow-lan: true" /etc/clash/config.yml
		#sed -i "5i\mode: Rule" /etc/clash/config.yml
		#sed -i "6i\log-level: info" /etc/clash/config.yml
		#sed -i "7i\external-controller: 0.0.0.0:9090" /etc/clash/config.yml
		#sed -i "8i\secret: '${da_password}'" /etc/clash/config.yml
		#sed -i "9i\ " /etc/clash/config.yml
		#sed -i "10i\ " /etc/clash/config.yml
		#sed -i "11i\ " /etc/clash/config.yml
		

		#if [ "$(uci get clash.config.en_mode 2>/dev/null)" = "redns" ]; then
		#	sed -i '/enhanced-mode:/ d' /etc/clash/config.yml
		#	sed -i '/fake-ip-range:/ d' /etc/clash/config.yml
		#	sed -i "/listen:/i\  enhanced-mode: redir-host" /etc/clash/config.yml 
		#
		#elif [ "$(uci get clash.config.en_mode 2>/dev/null)" = "fakeip" ]; then
		#	sed -i '/enhanced-mode:/ d' /etc/clash/config.yml
		#	sed -i '/fake-ip-range:/ d' /etc/clash/config.yml
		#	sed -i "/listen:/i\  enhanced-mode: fake-ip" /etc/clash/config.yml
		#	sed -i "/enhanced-mode: fake-ip/a\  fake-ip-range: 198.18.0.1/16" /etc/clash/config.yml	
		#fi	
		
		sed -i "/Proxy:/i\#clash-openwrt" /etc/clash/config.yml
        	sed -i "/#clash-openwrt/a\#=============" /etc/clash/config.yml
		sed -i '1,/#clash-openwrt/d' /etc/clash/config.yml		
		mv /etc/clash/config.yml /etc/clash/dns.yml
		cat /usr/share/clash/dns.yml /etc/clash/dns.yml > /etc/clash/config.yml 
		rm -rf /etc/clash/dns.yml
		sed -i "1i\port: 7890" /etc/clash/config.yml
		sed -i "2i\socks-port: 7891" /etc/clash/config.yml
		sed -i "3i\redir-port: ${proxy_port}" /etc/clash/config.yml
		sed -i "4i\allow-lan: true" /etc/clash/config.yml
		sed -i "5i\mode: Rule" /etc/clash/config.yml
		sed -i "6i\log-level: info" /etc/clash/config.yml
		sed -i "7i\external-controller: 0.0.0.0:9090" /etc/clash/config.yml
		sed -i "8i\secret: '${da_password}'" /etc/clash/config.yml
		sed -i "9i\external-ui: "/usr/share/clash/dashboard"" /etc/clash/config.yml
		sed -i "10i\ " /etc/clash/config.yml
		sed -i "11i\ " /etc/clash/config.yml
		sed -i '/#=============/ d' /etc/clash/config.yml
		
else

		sed -i "/dns:/i\#clash-openwrt" /etc/clash/config.yml
        	sed -i "/#clash-openwrt/a\#=============" /etc/clash/config.yml
		sed -i '1,/#clash-openwrt/d' /etc/clash/config.yml
		sed -i "1i\port: 7890" /etc/clash/config.yml
		sed -i "2i\socks-port: 7891" /etc/clash/config.yml
		sed -i "3i\redir-port: ${proxy_port}" /etc/clash/config.yml
		sed -i "4i\allow-lan: true" /etc/clash/config.yml
		sed -i "5i\mode: Rule" /etc/clash/config.yml
		sed -i "6i\log-level: info" /etc/clash/config.yml
		sed -i "7i\external-controller: 0.0.0.0:9090" /etc/clash/config.yml
		sed -i "8i\secret: '${da_password}'" /etc/clash/config.yml
		sed -i "9i\external-ui: "/usr/share/clash/dashboard"" /etc/clash/config.yml
		sed -i "10i\ " /etc/clash/config.yml
		sed -i "11i\ " /etc/clash/config.yml
		sed -i '/#=============/ d' /etc/clash/config.yml

fi
#=========================================================================================================================== 
}




yml_dns_change(){
#=========================================================================================================================== 
	   dns_port=`grep listen: /etc/clash/config.yml |awk -F ':' '{print $3}' |tr -cd "[0-9]"`
	   enhance=`grep enhanced-mode: /etc/clash/config.yml |awk -F ' ' '{print $2}'`	

	if [ $enhance == "redir-host" ]; then

	   if [ $dns_port -eq 53 ]; then
	          sed -i '/listen:/ d' /etc/clash/config.yml
	          sed -i "/nameserver:/i\  listen: 0.0.0.0:7894" /etc/clash/config.yml

		  dns_serve1=$(uci get dhcp.@dnsmasq[0].server 2>/dev/null)
		  if [ $dns_serve1 ]; then
			uci del dhcp.@dnsmasq[-1].server
		  fi
	          uci add_list dhcp.@dnsmasq[0].server=127.0.0.1#7894 >/dev/null 2>&1
	          uci delete dhcp.@dnsmasq[0].resolvfile
	          uci set dhcp.@dnsmasq[0].noresolv=1
	          uci commit dhcp
	    else
		  dns_serve1=$(uci get dhcp.@dnsmasq[0].server 2>/dev/null)
		  if [ $dns_serve1 ]; then
			uci del dhcp.@dnsmasq[-1].server
		  fi
	          uci add_list dhcp.@dnsmasq[0].server=127.0.0.1#$dns_port >/dev/null 2>&1
	          uci delete dhcp.@dnsmasq[0].resolvfile
	          uci set dhcp.@dnsmasq[0].noresolv=1
	          uci commit dhcp
	   fi

	else
		dns_serve1=$(uci get dhcp.@dnsmasq[0].server 2>/dev/null)
		if [ $dns_serve1 ]; then
			uci del dhcp.@dnsmasq[-1].server
		fi
	        #uci add_list dhcp.@dnsmasq[0].server=127.0.0.1#$dns_port >/dev/null 2>&1
		uci set dhcp.@dnsmasq[0].resolvfile=/tmp/resolv.conf.auto
		uci set dhcp.@dnsmasq[0].noresolv=0
		uci commit dhcp

	fi
#=========================================================================================================================== 	   
}



whitelist() {
#=========================================================================================================================== 
	(/usr/share/clash/chinaipset.sh && sleep 2 >/dev/null 2>&1) &
#=========================================================================================================================== 	
}

rules(){
#=========================================================================================================================== 
		LAN_IP=$(uci get network.lan.ipaddr)	
		dns_port=`grep listen: /etc/clash/config.yml |awk -F ':' '{print $3}' |tr -cd "[0-9]"`
		iptables -t nat -N clash               
		iptables -t nat -A clash -d 0.0.0.0/8 -j RETURN
		iptables -t nat -A clash -d 10.0.0.0/8 -j RETURN
		iptables -t nat -A clash -d 127.0.0.0/8 -j RETURN
		iptables -t nat -A clash -d 169.254.0.0/16 -j RETURN
		iptables -t nat -A clash -d 172.16.0.0/12 -j RETURN
		iptables -t nat -A clash -d 192.168.0.0/16 -j RETURN
		iptables -t nat -A clash -d 224.0.0.0/4 -j RETURN
		iptables -t nat -A clash -d 240.0.0.0/4 -j RETURN		

		iptables -t nat -N clash_dns

		iptables -t nat -A clash -p tcp --dport 22 -j ACCEPT

		iptables -t nat -A clash -p tcp -j REDIRECT --to-ports $proxy_port
		iptables -t nat -A clash -p udp -j REDIRECT --to-ports $dns_port

		iptables -t nat -A PREROUTING -p tcp -j clash
		iptables -t nat -A PREROUTING -p udp -j clash
		
		
#=========================================================================================================================== 
}	 


start_service(){
#=========================================================================================================================== 

enable=$(uci get clash.config.enable 2>/dev/null)

if [ $enable -eq 1 ]; then

	whitelist

   	proxy_port=$(uci get clash.config.proxy_port 2>/dev/null)
	
    	yml_change

	yml_dns_change
	
    	nohup $CLASH -d "$CLASH_CONFIG" > /tmp/clash.log 2>&1 &	
	  
	ln -s /usr/share/clash/web /www/clash
			
	uci set firewall.@defaults[0].flow_offloading=1
	uci commit firewall	
	/etc/init.d/firewall restart >/dev/null 2>&1
		
	rules
	
	killall -1 dnsmasq
	
	/etc/init.d/dnsmasq restart >/dev/null 2>&1

	
	if pidof clash >/dev/null; then
		add_cron
	else
	echo "===============================$(date "+%Y-%m-%d %H:%M:%S")  ERROR OCCURED =====================================" >> /tmp/clash.log
	fi
						
else

	echo "===============================$(date "+%Y-%m-%d %H:%M:%S")  CLASH IS DISABLED =====================================" >> /tmp/clash.log
			  
	
fi
#=========================================================================================================================== 
}



stop_service(){
#=========================================================================================================================== 
		iptables -t nat -F clash >/dev/null 2>&1
		iptables -t nat -X clash >/dev/null 2>&1
		iptables -t nat -F clash_dns >/dev/null 2>&1
		iptables -t nat -X clash_dns >/dev/null 2>&1
		iptables -t nat -D PREROUTING -p tcp -j clash >/dev/null 2>&1
		iptables -t nat -D PREROUTING -p udp -j clash >/dev/null 2>&1

		kill -9 `pidof clash|sed "s/$//g"` 2>/dev/null

	   	revert_dns
	
	  	uci set firewall.@defaults[0].flow_offloading=1
  	  	uci commit firewall
	  	/etc/init.d/firewall restart >/dev/null 2>&1
	
  	  	/etc/init.d/dnsmasq restart >/dev/null 2>&1
    
  	  	rm -rf /www/clash 2> /dev/null
	
  	  	del_cron
	
	 	rm -rf /tmp/clash.log
	
	
		echo "===============================$(date "+%Y-%m-%d %H:%M:%S")  CLASH STOPPED =====================================" >> /tmp/clash.log
	
#=========================================================================================================================== 	
}


restart(){
#=========================================================================================================================== 

		if pidof clash >/dev/null; then
			stop
			sleep 2
		    	start
		else
		    	start
		fi	

#=========================================================================================================================== 
}

